#+OPTIONS: LaTeX:t          Do the right thing automatically (MathJax)
#+OPTIONS: LaTeX:dvipng     Force using dvipng images
#+OPTIONS: LaTeX:nil        Do not process LaTeX fragments at all
#+OPTIONS: LaTeX:verbatim   Verbatim export, for jsMath or so
#+ATTR_HTML: width="10in"

% org-export-with-LaTeX-fragments



README.org --- description



Copyright (C) 2014 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>



  This file is part of mousecam.

  mousecam is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  mousecam is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with mousecam.  If not, see <http://www.gnu.org/licenses/>.



* Keywords:
mouse camera adns-2051 atmega i2c ocr optical recognition ai artificial intelligence



* Description:
  Проект предполагает создание устройства (камера от оптической мыши и
  микроконтроллера) которое обрабатывает изображение линий
  (соревнования роботов line-tracing) и выдаёт по шине i2c результат.
  Результат будет в виде координат или параметров линий, предполагаются следующие варианты:
  
  дуга-или-часть-круга x y r
  отрезок-или-линия (отрезок x1 y1 x2 y2)
  T-образное пересечение (отрезок x1 y1 x2 y2) (отрезок x3 y3 x4 y4)
  X-образное пересечение (отрезок x1 y1 x2 y2) (отрезок x3 y3 x4 y4)
  начало-или-конец-трассы (тут будут сложности)
  
* Usage:
use it



* History:
Project created at 2014-04(May)-18


* Dependences:
  

