#!/usr/bin/wish

# ZetCode Tcl/Tk tutorial
#
# This program draws three
# rectangles filled with different
# colors.
#
# author: Jan Bodnar
# last modified: March 2011
# website: www.zetcode.com


#canvas .can
#.can create rect 30 10 120 80     -outline #fb0 -fill #fb0
#.can create rect 150 10 240 80     -outline #f50 -fill #f50
#.can create rect 270 10 370 80     -outline #05f -fill #05f       
#pack .can 
#
#wm title . "colors" 
#wm geometry . 400x100+300+300





set baudrate   115200
set parity     n
set databits   8
set stopbits   1
set comPort    /dev/ttyUSB0

text .t1 -width 85 -font {courier 8 } -tabs {3c 6c 9c 13c left}\
    -cursor gobbler
pack .t1 -side top -anchor nw
button .b1 -text Exit -command exit
pack .b1 -side bottom -anchor nw -fill x -expand true
wm title . "Com1 Reader - HexCharacters "

.t1 tag configure underline -underline true
.t1 tag configure bold -font {courier 10 bold}
.t1 tag configure finsih -font {courier 6}
.t1 insert end "\tRead COM1: $baudrate, Parity=$parity,\
    Databits=$databits, Stopbits=$stopbits\n\n" {underline bold}


proc rd_chid {chid} {
    set msg [read $chid 3]
    set listOfLetters [split $msg {} ]
    set serialIPinHex ""
  
    foreach iChar $listOfLetters {
        scan $iChar "%c" decimalValue
        set hexValue [format "%02X" $decimalValue ]
        set hexValue "0x$hexValue"
        set serialIPinHex "$serialIPinHex $hexValue"
    }
    .t1 insert @0,0 "hallo:\"$serialIPinHex\"\n"   
}

proc open_com {} {
    global com
    global baudrate
    global parity
    global databits
    global stopbits
  
    set com [open $comPort r+]
    fconfigure $com -mode $baudrate,$parity,$databits,$stopbits -blocking 0 -translation auto -buffering none -buffersize 12
  
    fileevent $com readable [list rd_chid $com]
}

open_com

# the channel shouldn't be closed before exiting

#close $com
